### ISSUE TITLE
Class 'Hello\Providers\AppServiceProvider' not found.

### ISSUE THREAD

**Issue by bh-rat** [Mahmoudz/Hello-API#13]
I cloned the repository on my local machine and ran `composer install`. This is the exception that I got.
```
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Hello\Providers\AppServiceProvider' not found


Script php artisan optimize handling the post-install-cmd event returned with an error


  [RuntimeException]
  Error Output:


```
Am I missing something or is the repository still in development?

**Comment by Mahmoudz** [comment]
Hi @bh-rat Thank for cloning Hello API, 
I suggest you use this release `v0.1-alpha.8` instead of master now. Since I'm doing major updates to the project at this time. 
I will very soon get Master back to this `v0.1-alpha.8` release and create a `Develop` branch with my latest changes until it's stable. 
Thanks again.

**Comment by Mahmoudz** [comment]
@bh-rat if you still prefer to use the new structure on Master here's as quick fix for that you can go to the `config/app.php` and remove these lines:

```php
        Hello\Providers\AppServiceProvider::class,
        Hello\Providers\AuthServiceProvider::class,
        Hello\Providers\EventServiceProvider::class,
        Hello\Providers\RouteServiceProvider::class,
```

**Comment by Mahmoudz** [comment]
Hi again @bh-rat `Master` is not pointing to `v0.1-alpha.8` and `Develope` has the latest updates.. So if you clone again from `Master` now you should have the error solved. Also if you clone form `Develop` the error is solved, but more changes on that branch yet to come. 
Best,
