### ISSUE TITLE
User is created in database but it gives 409

### ISSUE THREAD

**Issue by siraj1044** [Mahmoudz/Hello-API#16]
When I register new user it gives me following error:
```
{
  "message": "Failed creating new User.",
  "status_code": 409
}
```

although user is created in database.

**Comment by Mahmoudz** [comment]
409 usually refers to Conflict. Probably you are registering an existing user! are you sure the email is unique? If so there's must be something causing the conflict in your request.

**Comment by siraj1044** [comment]
Yes i am trying with different email address and it creates record in database and give me 409 in response. Not sure whats the issue.

**Comment by Mahmoudz** [comment]
Can you check the Log file. And past it's content here as well. (please only the error related log).

This error is thrown from this **CreateUserTask** class (`App\Containers\User\Tasks\CreateUserTask`) line 65. You may want to debug there.

```php
        } catch (Exception $e) {
            throw (new AccountFailedException())->debug($e);
        }
```
