### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by rayoplateado** [Mahmoudz/Hello-API#4]
Hi! I'm just curious about Hello-API, reading the documentation I feel it's a really good starting point to create a brand new API using Laravel. So, I followed the installation instructions and everything seems to be fine. API responds. That's ok. The point is that the response from API is always 404.

```curl -X POST -H "Accept: application/json" -F "email=test@something.com" -F "password=secret#pass" -F "name=John Doe" "http://api.mega.pro/register"```

The answer is: 

`{"message":"404 Not Found","status_code":404}%`

Am I forgetting something?

**Comment by rayoplateado** [comment]
10 minutes. Sometimes I need to write my question to be conscious about how to solve the problem.

It's two variables in .env, APP_URL and API_DOMAIN. I forget to change API_DOMAIN to my own domain name.

Now seems to work perfectly.

**Comment by Mahmoudz** [comment]
Cool I'm glad you are using it and would love to hear your feedback :)

**Comment by ahmadbadpey** [comment]
This is my .env file content : 
```
APP_URL=hello.dev
APP_FULL_URL=http://hello.dev
API_DOMAIN=api.hello.dev
```

But every time that I send required values to `/register` , `404 Not Found` returned.
why?

**Comment by Mahmoudz** [comment]
@ahmadbadpey sorry for the delayed response, was very busy in the last 2 weeks..

Is this solved now, or you still need some help?!

**Comment by ahmadbadpey** [comment]
@Mahmoudz, I can not solve that yet. please help me.

**Comment by Mahmoudz** [comment]
@ahmadbadpey if you are trying to run `curl -X POST -H "Accept: application/json" -F "email=test@something.com" -F "password=secret#pass" -F "name=John Doe" "http://api.mega.pro/register"` maybe it's outdated now, I'll have to update that part of the documentation.. 

Your problem looks more like configs problem, I cannot tell what's wrong, I'll be manually testing all the code hopefully in the next 3 weeks. But I can advise you to re-check your `host` file, as the subdomain needs to be defined there.

**Comment by Mahmoudz** [comment]
@ahmadbadpey this part of the documentation is now updated visit [here](https://hello-api.readme.io/v5.2.0/docs/installation#5-testing). The endpoint have became `http://api.hello.dev/user/register` instead of `http://api.hello.dev/register`

**Comment by ahmadbadpey** [comment]
@Mahmoudz , I tried that but a new problem occurred. 

I think that configurations are not Problematic beacause when send request to `http://api.hello.dev/` the `"Welcome to Hello API."` is shown. 

Of course I am using Postman as client to send request and now when send email, password, name data to `http://api.hello.dev/user/register` bellow errror is shown : 
```
{
  "message": "syntax error, unexpected '->' (T_OBJECT_OPERATOR)",
  "code": 4,
  "status_code": 500
}
```

**Comment by Mahmoudz** [comment]
@ahmadbadpey I will check that. Do you have the latest version of Hello Api?!

**Comment by ahmadbadpey** [comment]
@Mahmoudz , Yes I'm using v0.3.0.

**Comment by Mahmoudz** [comment]
Oh I currently only support the master branch. Until I make the first stable release.. I won't be able to find out why you are having this problem because things have changed a lot since then, but once I reach the stable release, there shouldn't be major changes and will have multiple versions so you we can all track everything.. Thanks for using Hello API. Best,

**Comment by rockers007** [comment]
@Mahmoudz :any update on this issue?

**Comment by Mahmoudz** [comment]
@rockers007 the 404 problem is almost always configuration issue form the user side. I will put more effort in making this easier and easier.

I saw ur other issue so I assume you solve it!? if not make sure the values in the `.env` file are matching your domain.
