### ISSUE TITLE
Q: Have you planned to have official release?

### ISSUE THREAD

**Issue by llstarscreamll** [Mahmoudz/Hello-API#44]
Hi!! Very very powerful setup!! I'm here to know if have you planned to have an official release soon?

Thank you!! ^_^

**Comment by Mahmoudz** [comment]
@llstarscreamll thanks for your feedback. Sure I'm planning to have an official release, but really don't know when exactly! However, I guess it should be within the next **50 days**.

These steps must be done before the release:
- Enhance the [Porto](https://github.com/Mahmoudz/Porto) documentation (which I started already).
- Organize the Hello API [documentation](hello-api.readme.io), and add a lot more details to it. (I started by cleaning the existing docs).
- Refactor the code, line by line. And make sure everything is in the right place.

After the first release I guess will work on the Automatic Code Generator, which should build the entire Container for you.
