### ISSUE TITLE
Upgrade to Laravel 5.3

### ISSUE THREAD

**Issue by Mahmoudz** [Mahmoudz/Hello-API#47]

**Comment by g0ld3lux** [comment]
already updated? or still pending... would like to test 5.3

**Comment by Mahmoudz** [comment]
@g0ld3lux still pending, I'm not sure I will have time to do this before the first stable release milestone, but I'll try.

**Comment by dugajean** [comment]
Would love to give this product of yours a try, but I'm gonna wait for the 5.3 version before continuing. There's a clearer separation by default between web and api apps in 5.3.

**Comment by Mahmoudz** [comment]
@dugajean 100% I'm very excited to 5.3 for that reason, and I'm sure this upgrade is not gonna be simple, it's gonna take me some time :( I'm about to start yet another project on top of Hello API I'll try to upgrade it before I start. So It's either this week or after 2 month :P when I finish this project.

**Comment by Mahmoudz** [comment]
@g0ld3lux @dugajean Hello API is now running on Laravel 5.3 surprisingly it took me less than 4 hours! to upgrade the code and the docs in addition to cleaning few things along the way.

It worth also mentioning few things that were already implemented in Hello API since version 5.1 and now supported in 5.3 by default:

- Separation of Routes files (Web and API)
- Treating the Console commands as an Interface, like we do in UI > CLI.
- Supporting multiple files paths (such as for Migrations).
- Adding Providers directory which we already have in every container.
- Mailable (Classes to define Emails), Laravel's version is much cleaner.
- Ordering the service providers in the app config providers with comments between them.

**Comment by g0ld3lux** [comment]
Ill test it let me know how can i help with the documentation.... 
Examples... etc... this is worth maintaining like laradock ...

**Comment by llstarscreamll** [comment]
OMG!! It means that the project is ready to production?

**Comment by Mahmoudz** [comment]
@llstarscreamll not yet, I'm still doing some major changes #45. 

I will be working on Hello API for 3 days (started yesterday) after that I have to build a project for a client and will take me ~2 months before doing another major updates..

I'll create a stable version in the next few days as stated by this Milestone https://github.com/Mahmoudz/Hello-API/milestone/1

Besttt
