### ISSUE TITLE
ModelsFactory doesn't support multiple models in container

### ISSUE THREAD

**Issue by twcarefoot** [Mahmoudz/Hello-API#48]
see ModelsFactory.php. It assumes only one model factory per Container. 
```
if (is_dir($containersDirectory)) {
        $containerFactoryFile = $containersDirectory . $containerName . 'Factory.php';

        if (is_file($containerFactoryFile)) {
            include($containerFactoryFile);
        }
    }
```

How do I register multiple model factories per container?

**Comment by Mahmoudz** [comment]
@twcarefoot nice catch, I'll make this support multi models factories. If you need this as soon as possible, feel free to submit a PR.. I will try to support that within the next 8 days.

**Comment by Mahmoudz** [comment]
Closed https://github.com/Mahmoudz/Hello-API/commit/33fce9b08a253ad534591dc3cef179f995920cad
