### ISSUE TITLE
support laravel multi auth 

### ISSUE THREAD

**Issue by engAhmad** [Mahmoudz/Hello-API#49]
Is this repository  support laravel multi  auth ?

if not here you can find the implementation 

[ 1- Using JWTGuard with Laravel 5.2.x](https://github.com/tymondesigns/jwt-auth/issues/513#issuecomment-186087297)

[ 2- jwt-auth-guard](https://github.com/irazasyed/jwt-auth-guard)

**Comment by Mahmoudz** [comment]
Hi @engAhmad what do you mean by multi auth?
We do support authentication for API's using JWT. and authentication for Web using the default Laravel auth. In addition we do also support social authentication for the API.

**Comment by engAhmad** [comment]
laravel 5.2 and above ships with authentication guards in hello api you can only use users model to be Authenticatable  using jwt  as a driver  Suppose , for example you have customers model and should be Authenticatable .

**Comment by Mahmoudz** [comment]
Ahh ok, if it's in Laravel 5.2 then it's supported. So the answer is yes, but I personally never used it.

**Comment by engAhmad** [comment]
"tymon/jwt-auth": "0.5.*", dose not supported this feature 
only "tymon/jwt-auth": "^1.0@dev", branch works
