### ISSUE TITLE
Application In Production! while database migrate

### ISSUE THREAD

**Issue by shadyk** [Mahmoudz/Hello-API#5]
I am following the installation step by step and when I tried to migrate the database : 
php artisan migrate

i got 

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? [y/N] (yes/no) [no]:
 > y

                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by Mahmoudz** [comment]
@shadyk thanks for using this project.

before you are able to call that migration (`php artisan migrate`), you must publish the Module Migrations to the Framework migrations directory.

Example of publishing the User Module Migrations: `php artisan vendor:publish --provider="Mega\Modules\User\Providers\UserServiceProvider"`

So just run this and then try again. 

This is mentioned in the Notes section of https://github.com/Mahmoudz/Hello-API/wiki/Database-Migrations.

I will update the Installation steps to cover that in a more clear way.

Regarding the PDO exception this is usually due the missing the PDO installation on your server or could be installed but misconfigured. Try using this project ([LaraDock](https://github.com/LaraDock/laradock)) to make your life easier and to manage your server environment in a very easy way. LaraDock is tested and run smoothly with Hello API. 

Best,

**Comment by shadyk** [comment]
Hello again,

Your solution worked but not totally when i tried to migrate I now get another error 
php artisan migrate

                                              
  [PDOException]                              
  SQLSTATE[HY000] [2002] Operation timed out


It is timing out after 10 sec

**Comment by Mahmoudz** [comment]
not sure why! but try switching `127.0.0.1` with `localhost ` and vice versa in your config files.
