### ISSUE TITLE
PortServiceProviderTrait wrong directory in publisher

### ISSUE THREAD

**Issue by twcarefoot** [Mahmoudz/Hello-API#50]
Line 150 of app/Port/Provider/Traits/PortServiceProviderTrait.php has

> private function publishModuleMigrationsFiles($containerName)
>     {
>         **$containerMigrationsDirectory = base_path() . '/app/Containers/' . $containerName . '/Database/Migrations/';**
>         if (is_dir($containerMigrationsDirectory)) {
>             $this->publishes([
>                 $containerMigrationsDirectory => database_path('migrations'),
>             ], 'migrations');
>         }
>     }

Shouldn't it be "/Data"?

**Comment by Mahmoudz** [comment]
@twcarefoot absolutely, I forget to update that after renaming the Data folder. Thank you I fixed it now #d489d3b7fa063440b41905258495e49550bdbb64
