### ISSUE TITLE
What migrations are used?

### ISSUE THREAD

**Issue by denizdogan** [Mahmoudz/Hello-API#52]
A lot of (all?) containers have their migrations duplicated to /database/migrations, what are they for? Which migrations are run by `php artisan migrate`?

Where should I put new migrations for new containers?

**Comment by Mahmoudz** [comment]
@denizdogan Migrations should be created inside the Container, then published to the framework`/database/migrations` using `php artisan vendor:publish --force --provider="App\Port\Provider\Providers\PortServiceProvider"`. 

When you run `php artisan migrate` it reads them from `/database/migrations`. Just like Vendor Packages, every package has its own migrations and then they get published to the framework with `php artisan vendor:publish`. For more info about that read [this](https://hello-api.readme.io/docs/migrations).

I'm wish to delete the `/database/migrations` and only use the container migrations, if you have any solution/trick for that feel free to contribute.
