### ISSUE TITLE
Documentation error? Receiving Illuminate\Http\Exception\HttpResponseException

### ISSUE THREAD

**Issue by denizdogan** [Mahmoudz/Hello-API#53]
https://hello-api.readme.io/docs/requests

"All Requests MUST extend from App\Porto\Request\Abstracts\Request"

```php
<?php
namespace App\Containers\Exam\UI\API\Requests;

use App\Port\Request\Abstracts\Request; // <- !

class GetExamByIdRequest extends Request
{
    public function rules()
    {
        return [];
    }
}
```

The above request class gives me a strange HttpResponseException for no obvious reason. When I subclass `Dingo\Api\Http\Request` instead, everything works as expected. Is the documentation outdated?

Thanks for the great work btw

**Comment by denizdogan** [comment]
Further investigation shows that if I subclass `App\Port\Request\Abstracts\Request`, I *must* also implement `authorize`. Then it works.

**Comment by Mahmoudz** [comment]
@denizdogan well I'm not able to check that now :P but what should I fix in the Documentation?!

**Comment by denizdogan** [comment]
@Mahmoudz: Thanks, I feel like we can close this issue now.

In the future development of Hello API, maybe we could refactor some things about the way Request objects work? Too often I have to override the `all` method, which feels like a hack. It's like URL parameters are second-class citizens compared to "real" parameters, but many routes use *only* URL parameters! :)

**Comment by Mahmoudz** [comment]
@denizdogan 100% that needs refactoring, so far the only working solution for that is to hack the `all()` function. Maybe we can add some nice function in Hello API for that or contribute to the Laravel core with a nicer solution..
