### ISSUE TITLE
Maintain the namespace Mega

### ISSUE THREAD

**Issue by pcottrell** [Mahmoudz/Hello-API#6]
Hey Mahmoud,

Do you plan on this package maintaining the namespace Mega?

Cheers,
Paul C.

**Comment by Mahmoudz** [comment]
I will consider changing it to another name like Hello.. The project was named Mega Pro before publishing on Github then it was renamed to Hello API, however it's very easy to change it by using the "replace all" in your IDE. But you'll have to keep doing this for every "pull".

**Comment by pcottrell** [comment]
I like the Hello API name :) good call on the change.
