### ISSUE TITLE
Upgrade to Laravel 5.2

### ISSUE THREAD

**Issue by Mahmoudz** [Mahmoudz/Hello-API#7]
Include upgrading steps in the docs for future upgrades.

**Comment by pcottrell** [comment]
Do you think laravel will push to another version and call it LTS?

**Comment by Mahmoudz** [comment]
Not soon! maybe 6.1!! but some people are excited about features in 5.2 and 5.3, so I might have to keep upgrading it to the latest release. I believe upgrading should be simple and easy.

**Comment by pcottrell** [comment]
What version do you recommend running with Hello-API?

**Comment by Mahmoudz** [comment]
I really have no preference! 5.1 is great because of the LTS it has, but if you need some 5.2/5.3 features you might consider upgrading.

**Comment by Mahmoudz** [comment]
#39 w'll upgrade to 5.3 once it's released.
